/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        // App classUnderTest = new App();
        // assertNotNull(classUnderTest.getGreeting("foo"), "app should have a greeting");
        int a = 1;
        int b = 2;
        assertEquals(3, a + b);
    }
}
